name: Upload zip
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make release zip
      run: |
        wget https://github.com/topjohnwu/Magisk/raw/master/scripts/module_installer.sh -O META-INF/com/google/android/update-binary
        rm -rf '*.git*'
        zip -9 -r ../wifi_bonding_plus_dfs.zip ./
        sha256sum ../wifi_bonding_plus_dfs.zip > ../wifi_bonding_plus_dfs.zip.sha256sum
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ../wifi_bonding_plus_dfs.zip
          ../wifi_bonding_plus_dfs.zip.sha256sum
    - uses: actions/upload-artifact@v4
      with:
        name: wifi_bonding_plus_dfs.zip
        path: ./
